# Generated by Django 6.1.1 on 2026-09-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interna', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_de_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('G', 'Gramos'), ('M', 'Metros'), ('CM', 'Centímetros'), ('UN', 'Unidad')], default='UN', max_length=20),
        ),
    ]
