# Generated by Django 6.1.1 on 2026-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interna', '0003_alter_materiaprima_unidad_de_medida'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productomateriaprima',
            constraint=models.UniqueConstraint(fields=('producto', 'materia_prima'), name='producto_materia_prima_unica'),
        ),
    ]
