# Generated by Django 6.1.1 on 2026-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interna', '0004_productomateriaprima_producto_materia_prima_unica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
    ]
