# Generated by Django 6.1.1 on 2026-10-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interna', '0005_alter_producto_stock_actual'),
        ('interna', '0005_pedido_detallepedido'),
    ]

    operations = [
    ]
